on:
  push:
    branches: master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        uses: Devleaps/jsonresume-generator@v1
        name: Convert Resume to HTML
        with:
          action: "render"
          file: "en.json"
          folder: "cv"
          output-type: "html"
          theme-name: "jsonresume-theme-kendall"
      -
        name: Convert HTMLResume to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: cv/en.html
          outputFile: cv/en.pdf
      -
        name: Copy Resume
        run: |
          cp cv/en.html toni-barth.online/pages/resume.html
          cp cv/en.pdf toni-barth.online/files/CV_Toni_Barth.pdf
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: "Log in to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: tonironaldbarth/toni-barth.online:latest
